src/main/java/com/ellepharma/web/MB/BaseMB.java
package com.ellepharma.web.MB;

import com.ellepharma.utils.JsfUtils;
import com.ellepharma.utils.Utils;

import javax.el.ELContext;
import javax.el.ExpressionFactory;
import javax.el.ValueExpression;
import javax.faces.application.Application;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.Serializable;
import java.util.Map;

/**
 * BaseMB.java
 *
 * @author Malek Yaseen <malek.m.yaseen@gmail.com>
 * @since Apr 21, 2019
 */
public class BaseMB implements Serializable {

    private static final long serialVersionUID = 1L;
    private boolean editMode;
    private boolean viewMode;

	public void addSuccessMessage() {
		JsfUtils.addSuccessMessage();

	}

	public void addSuccessMessage(String key) {
		JsfUtils.addSuccessMessage(key);

	}

	public void addErrorMessage(Exception e) {
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, Utils.getMsg("common.addErrorMessage") + " " + e.getMessage(),
				null);
		FacesContext context = FacesContext.getCurrentInstance();
		context.addMessage("growl", message);
		JsfUtils.update("form_messages");

	}

	public void addErrorMessage(String key) {
		JsfUtils.addErrorMessage(key);

	}

	public void addWarningMessage(String key) {
		JsfUtils.addWarningMessage(key);

	}

    public void addErrorMessage(String key, UIComponent component) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, Utils.getMsg(key), null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(component.getClientId(), message);
    }

    public void addErrorMessage(String key, String id) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, Utils.getMsg(key), null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(id, message);
    }

    public void addWarningMessage(String key, UIComponent component) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_WARN, Utils.getMsg(key), null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(component.getClientId(), message);
    }

    public void addInfoMessage(String key) {
        keepMessage();
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, Utils.getMsg(key), null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage("growl", message);
    }
    public void addDirectInfoMessage(String msg) {
        keepMessage();
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, msg, null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage("growl", message);
    }

    public void addInfoMessage(String key, String id) {
        FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, Utils.getMsg(key), null);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(id, message);
    }

    public void showDialog(String dialogVar) {
        JsfUtils.openDialog(dialogVar);
    }


    public void updates(String... componentIds) {
            JsfUtils.update(componentIds);
    }

    public void hideDialog(String dialogVar) {
        JsfUtils.hideDialog(dialogVar);
    }

    public void keepMessage() {
        JsfUtils.keepMessage();
    }

    protected HttpSession getSession(boolean create) {
        return (HttpSession) getExternalContext().getSession(create);
    }

    protected FacesContext getContext() {
        return FacesContext.getCurrentInstance();
    }

    protected ExternalContext getExternalContext() {
        return FacesContext.getCurrentInstance().getExternalContext();
    }

    protected HttpServletRequest getHttpServletRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
    }

    protected HttpServletResponse getHttpServletResponse() {
        return (HttpServletResponse) FacesContext.getCurrentInstance().getExternalContext().getResponse();
    }

    protected ServletContext getServletContext() {
        return (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
    }

    protected String getRequestParam(String name) {
        return getContext().getExternalContext().getRequestParameterMap().get(name);
    }

    protected Map<String, Object> getSessionMap(String name) {

        Map<String, Object> sessionMap = getExternalContext().getSessionMap();

        return (Map<String, Object>) sessionMap.get(name);
    }

    protected ELContext getELContext() {
        return getContext().getELContext();
    }

    protected Application getApplication() {
        return getContext().getApplication();
    }

    protected ExpressionFactory getExpressionFactory() {
        return getApplication().getExpressionFactory();
    }

    protected Object getELValue(Object base, Object property) {
        return getELContext().getELResolver().getValue(getELContext(), base, property);
    }

    public static void setExpressionValue(final Object value, final String expression) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        ELContext elContext = facesContext.getELContext();

        ValueExpression targetExpression = facesContext.getApplication().getExpressionFactory()
                .createValueExpression(elContext, expression, Object.class);
        targetExpression.setValue(elContext, value);
    }

    public static Object getExpressionValue(final String expression) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        ELContext elContext = facesContext.getELContext();

        ValueExpression targetExpression = facesContext.getApplication().getExpressionFactory()
                .createValueExpression(elContext, expression, Object.class);
        return targetExpression.getValue(elContext);
    }

    public boolean isEditMode() {
        return editMode;
    }

    public void setEditMode(boolean editMode) {
        this.editMode = editMode;
    }

    public boolean isViewMode() {
        return viewMode;
    }

    public void setViewMode(boolean viewMode) {
        this.viewMode = viewMode;
    }

    public String getCurrentLanguage() {
        return Utils.getCurrentLang().getLocale();
    }
}

src/main/webapp/resources/components/orderItems.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:elle="http://java.sun.com/jsf/composite/components">

<p:dialog widgetVar="dlgProductItem" id="dlgProductItem" modal="true" blockScroll="true"
          closeOnEscape="true" maximizable="true" dynamic="true"
          showEffect="fade" hideEffect="fade" style="max-width: 70%"
          position="center center">
    <f:facet name="header">
        <h:outputLabel id="headerOrder" value="#{msg['common.orderDetails']}  #  :#{accountMB.selectedOrder.id}"/>
    </f:facet>
    <h:form id="ProductItemFrm">
        <p:messages id="form_messages"/>

        <div class="ui-g-12 ui-lg-12">
            <div class="card card-w-title">


                <div class="ui-fluid">
                    <div class="ui-g">
                        <div class="ui-g-12">

                            <p:panelGrid columns="6"
                                         columnClasses="ui-grid-col-2 diffColor,ui-grid-col-2, diffColor ui-grid-col-2  ,ui-grid-col-2, diffColor ui-grid-col-2,ui-grid-col-2"
                                         layout="grid"
                                         styleClass="ui-panelgrid-blank form-group"
                                         style="border:0px none; background-color:transparent;">


                                <h:outputLabel value="رقم الطلب :"/>
                                <h:outputLabel value="#{accountMB.selectedOrder.id}"/>
                                <h:outputLabel value="رقم الفاتورة :"/>
                                <h:outputLabel value=" #{utils.formatInvoice(accountMB.selectedOrder.invoiceNo)}"/>

                                <h:outputLabel value=" التاريخ: "/>
                                <h:outputText value="#{accountMB.selectedOrder.creationDate}">
                                    <f:convertDateTime pattern="MM/dd/yyyy hh:mm:ss a"/>
                                </h:outputText>

                                <h:outputLabel value="#{msg['common.cartTotals']} :"/>
                                <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}"
                                                        value="#{accountMB.selectedOrder.total}"/>


                                <h:outputLabel value="#{msg['common.couponNumber']} :"/>
                                <p:outputLabel value="#{accountMB.selectedOrder.coupon.couponNumber}"/>

                                <h:outputLabel value="#{msg['common.discount']} :"/>
                                <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}"
                                                        value="#{accountMB.selectedOrder.discount}"/>


                                <h:outputLabel value="#{msg['common.shipping']} :"/>
                                <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}"
                                                        value="#{accountMB.selectedOrder.shippingFee}"/>

                                <h:outputLabel value="#{msg['common.payment-type.fee']} :"/>
                                <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}"
                                                        value="#{accountMB.selectedOrder.paymentFee}"/>

                                <h:outputLabel value="#{msg['common.orderTotal']} :"/>
                                <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}"
                                                        value="#{accountMB.selectedOrder.total-accountMB.selectedOrder.discount +accountMB.selectedOrder.shippingFee +accountMB.selectedOrder.paymentFee}"/>
                                <h:outputLabel value="#{msg['common.payment-type']} :"/>

                                <h:outputLabel
                                        value="#{accountMB.selectedOrder.paymentType.desc[accountMB.selectedOrder.languageCode]}"/>

                                <h:outputLabel value="#{msg['common.paymentStatus']} :"/>
                                <h:outputLabel
                                        value="#{msg['tnc'.concat(accountMB.selectedOrder.paymentStatus.code)]}"/>

                                <h:outputLabel value="#{msg['common.shipmentStatus']} :"/>
                                <h:outputLabel
                                        value="#{accountMB.selectedOrder.shipmentStatus.name()}"/>

                                <h:outputLabel value="#{msg['common.customerName']} :"/>
                                <p:commandLink
                                        action="#{accountMB.viewAccountDetails(accountMB.selectedOrder.account.id)}">

                                    <h:outputLabel value="#{accountMB.selectedOrder.account.fullName}"/>
                                </p:commandLink>

                                <h:outputLabel value="#{msg['common.aramexTrackingNumber']} :"/>
                                <h:outputLabel value="#{accountMB.selectedOrder.tracking}"/>


                            </p:panelGrid>
                        </div>
                    </div>
                </div>
                <p:dataTable var="orderItem"
                             value="#{accountMB.selectedOrder.productList}"
                             id="orderItemDtl" paginatorPosition="bottom" reflow="true"
                             dir="#{guestPreferences.getDir()}"

                             emptyMessage="#{msg['common.NoData']}" rowIndexVar="index"
                             paginatorAlwaysVisible="false"
                             currentPageReportTemplate="#{msg['common.showing']}
                                      {startRecord} - {endRecord} #{msg['common.of']}  {totalRecords}"
                             paginatorTemplate="{RowsPerPageDropdown} {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} "
                             rowKey="#{orderItem.id}" paginator="true" rowsPerPageTemplate="5,10,15,25"
                             rows="5">

                    <p:column headerText="#" width="50">#{index+1}</p:column>
                    <p:column headerText="#{msg['common.barcode']}" sortable="true"
                              filterBy="#{orderItem.item.barcode}"
                              sortBy="#{orderItem.item.barcode}"> #{orderItem.item.barcode}</p:column>


                    <p:column headerText="#{msg['common.productName']}" sortable="true"
                              filterBy="#{orderItem.item.name.get(orderItem.currentLanguage)}"
                              filterable="true"
                              filterMatchMode="contains"
                              sortBy="#{orderItem.item.name.get(orderItem.currentLanguage)}">#{orderItem.item.name.get(orderItem.currentLanguage)}</p:column>


                    <p:column headerText="#{msg['common.price']}" sortable="true"
                              filterBy="#{orderItem.price}"
                              sortBy="#{orderItem.price}">
                    <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}" value="#{orderItem.price}" />
                    </p:column>
                    <p:column headerText="#{msg['common.qty']}" sortable="true"
                              filterBy="#{orderItem.qty}"
                              sortBy="#{orderItem.qty}"> #{orderItem.qty}</p:column>

                    <p:column headerText="#{msg['common.tax']}" sortable="true" rendered="false"
                              filterBy="#{orderItem.tax}"
                              sortBy="#{orderItem.tax}"> #{orderItem.tax}</p:column>

                    <p:column headerText="#{msg['common.total']}" sortable="true"
                              filterBy="#{orderItem.total}"
                              sortBy="#{orderItem.total}"> <elle:priceWitouConvert code="#{accountMB.selectedOrder.currency.currencyCode}" value="#{orderItem.total}" /> </p:column>
                </p:dataTable>
            </div>

        </div>
    </h:form>

    <p:ajax event="close" immediate="true" update="@parent @this dlgProductItem" global="false"
            resetValues="true"/>
</p:dialog>


<p:dialog widgetVar="dlgAccountDetails" id="dlgAccountDetails" modal="true" blockScroll="true"
          closeOnEscape="true" maximizable="true" dynamic="true" appendTo="@(body)"
          showEffect="fade" hideEffect="fade" style="max-width: 100%" width="600px"
          position="center center">
    <f:facet name="header">
        <h:outputLabel id="headerdlgAccountDetails"
                       value="#{msg['common.accountDetails']}  #  :#{accountMB.orderAccountDetails.fullName}"/>
    </f:facet>
    <h:form id="dlgAccountDetailsFrm">
        <p:messages id="form_messages"/>

        <div class="ui-g-12 ui-lg-12">
            <div class="card card-w-title">


                <div class="ui-fluid">
                    <div class="ui-g">
                        <div class="ui-g-12">

                            <p:panelGrid columns="2"
                                         columnClasses="ui-grid-col-4 diffColor,ui-grid-col-8, diffColor ui-grid-col-2  ,ui-grid-col-2, diffColor ui-grid-col-2,ui-grid-col-2"
                                         layout="grid"
                                         styleClass="ui-panelgrid-blank form-group"
                                         style="border:0px none; background-color:transparent;">


                                <h:outputLabel value="#{msg['common.name']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.fullName}"/>
                                <h:outputLabel value="#{msg['common.gender']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.genderEnum.name()}"/>

                                <h:outputLabel value="#{msg['common.country']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.country.desc}"/>

                                <h:outputLabel value="#{msg['common.city']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.city}"/>

                                <h:outputLabel value="#{msg['common.state']} : "/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.state}"/>

                                <h:outputLabel value="#{msg['common.postcode']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.postcode}"/>
                                <h:outputLabel value="#{msg['common.address']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.address}"/>

                                <h:outputLabel value="#{msg['common.email']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.email}"/>

                                <h:outputLabel value="#{msg['common.phone']} :"/>
                                <h:outputLabel value="#{accountMB.orderAccountDetails.phone.replaceAll(' ','')}"/>


                            </p:panelGrid>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </h:form>
</p:dialog>

<h:outputStylesheet>
    .diffColor {

        background-color: #E0E0E0;

    }
</h:outputStylesheet>

</html>

src/main/webapp/resources/components/outputText.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
>

<cc:interface componentType="cust.outputText">
</cc:interface>

<cc:implementation>
	<span id="#{cc.clientId}"> <h:outputText id="lang1Output"/>
	</span>
</cc:implementation>

</html>

src/main/webapp/resources/components/price.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite" xmlns:f="http://java.sun.com/jsf/core">

<cc:interface>
    <cc:attribute name="value" required="true"/>
    <cc:attribute name="qty" required="false"/>
    <cc:attribute name="pattern" required="false"/>
</cc:interface>

<cc:implementation>
    <h:outputText value="#{cc.attrs.value}" qty="#{cc.attrs.qty}">

        <f:converter converterId="priceConverter"/>
    </h:outputText>
</cc:implementation>

</html>

src/main/webapp/resources/components/priceWitouConvert.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite" xmlns:f="http://java.sun.com/jsf/core">

<cc:interface>
    <cc:attribute name="value" required="true"/>
    <cc:attribute name="qty" required="false"/>
    <cc:attribute name="code" required="false" default="#{currentCurrency.currencyCode}"/>
    <cc:attribute name="pattern" required="false" default="###,###,###.###"/>
</cc:interface>

<cc:implementation>


    <div>

    <h:outputText  dir="LTR" id="value1" value="#{cc.attrs.value}" style="text-align: left!important;">
        <f:convertNumber pattern="###,###,###.###" type="number" />
    </h:outputText>
    <h:outputText styleClass="ss" value=" #{cc.attrs.code}" />
    </div>


</cc:implementation>

</html>

src/main/webapp/resources/components/translator.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:p="http://primefaces.org/ui" xmlns:h="http://xmlns.jcp.org/jsf/html"
>

<cc:interface componentType="translator">
    <cc:attribute name="value" required="false"/>
    <cc:attribute name="label" required="true" type="java.lang.String"/>
    <cc:attribute name="help" required="false" type="java.lang.Object"/>
    <cc:attribute name="disabled" required="false"/>
    <cc:attribute name="modal" required="false" default="true"/>
    <cc:attribute name="columnClasses" required="false" default="ui-grid-col-6,ui-grid-col-6"/>
    <cc:attribute name="columns" required="false" default="2"/>
    <cc:attribute name="required" type="java.lang.Boolean" default="true"/>
    <cc:attribute name="nextTabindex1"/>
    <cc:attribute name="nextTabindex2"/>
</cc:interface>

<cc:implementation>

    <p:panelGrid columns="#{cc.attrs.columns}" columnClasses="#{cc.attrs.columnClasses}" layout="grid"
                 styleClass="ui-panelgrid-blank form-group" style="border:0px none; background-color:transparent;">
        <h:panelGroup styleClass="translate-md-inputfield">

            <p:outputLabel id="lang1Lbl" value="#{cc.attrs.label} ( ع )" for="lang1Input"/>
            <p:inputText required="#{cc.attrs.required}" id="lang1Input" disabled="#{cc.attrs.disabled}"
                         styleClass="input-trans"/>
            <p:commandButton id="moreBtn" icon="ui-icon-translate" original="true" styleClass="btn-trans"
                             update="extraLangsDlgPnlGrd" process="@this" widgetVar="moreBtn#{cc.clientId}"
                             onclick="PF('extraLangsDlg#{cc.clientId}Var').show();" style="position: absolute;"/>
        </h:panelGroup>
        <h:panelGroup styleClass="translate-md-inputfield">
            <p:outputLabel id="lang2Lbl" value="#{cc.attrs.label} ( En )" for="lang2Input"/>
            <p:inputText required="#{cc.attrs.required}" id="lang2Input" disabled="#{cc.attrs.disabled}"/>
        </h:panelGroup>
    </p:panelGrid>

    <p:dialog id="extraLangsDlg" header="#{msg['common.otherLanguages']}"
              widgetVar="extraLangsDlg#{cc.clientId}Var" modal="#{cc.attrs.modal}" closeOnEscape="true"
              styleClass="favOverLay">
        <p:defaultCommand target="okBtn" scope="extraLangsDlg" rendered="#{!cc.attrs.disabled}"/>
        <p:panelGrid id="extraLangsDlgPnlGrd" columns="2">
            <p:commandButton id="okBtn" value="#{msg['common.done']}" process="extraLangsDlgPnlGrd"
                             rendered="#{!cc.attrs.disabled}" update="extraLangsDlgPnlGrd" original="true"
                             tabindex="#{guestPreferences.languageList.size()}"
                             onclick="PF('extraLangsDlg#{cc.clientId}Var').hide();"
                             style="width: 100%"/>
        </p:panelGrid>
    </p:dialog>

    <script type="application/javascript">
        $($(PrimeFaces.escapeClientId("#{cc.clientId}:lang1Input"))).keydown(function (e) {
            if ('#{cc.attrs.nextTabindex1}') {
                if (!e.shiftKey &amp;&amp; e.keyCode == 9) {
                    $("input[id*='#{cc.attrs.nextTabindex1}']").attr('back', this.id);
                    $("input[id*='#{cc.attrs.nextTabindex1}']").focus();
                    return false;
                } else if (e.shiftKey &amp;&amp; e.keyCode == 9) {
                    var idB = $(this).attr('back');
                    if (idB)
                        $(PrimeFaces.escapeClientId(idB)).focus();
                    return false;
                }
            }
        });
        $($(PrimeFaces.escapeClientId("#{cc.clientId}:lang2Input"))).keydown(function (e) {
            if ('#{cc.attrs.nextTabindex2}') {
                if (!e.shiftKey &amp;&amp; e.keyCode == 9) {
                    $("input[id*='#{cc.attrs.nextTabindex2}']").focus();
                    $("input[id*='#{cc.attrs.nextTabindex2}']").attr('back', this.id);

                    return false;
                } else if (e.shiftKey &amp;&amp; e.keyCode == 9) {
                    var idB = $(this).attr('back');
                    if (idB)
                        $(PrimeFaces.escapeClientId(idB)).focus();
                    return false;
                }
            }
        });
    </script>
</cc:implementation>

</html>

src/main/webapp/resources/components/translatorTextArea.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:cc="http://xmlns.jcp.org/jsf/composite"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui">

<cc:interface componentType="translator">
    <cc:attribute name="label" required="true" type="java.lang.String"/>
    <cc:attribute name="help" required="false" type="java.lang.Object"/>
    <cc:attribute name="disabled" required="false"/>
    <cc:attribute name="columnClasses" required="false" default="ui-grid-col-4,ui-grid-col-7"/>
    <cc:attribute name="required" type="java.lang.Boolean" default="true"/>
    <cc:attribute name="cols" type="java.lang.Integer" default="20"/>
    <cc:attribute name="rows" type="java.lang.Integer" default="3"/>
    <cc:attribute name="nextTabindex1"/>
    <cc:attribute name="nextTabindex2"/>
</cc:interface>

<cc:implementation>
	<span id="#{cc.clientId}"> <p:panelGrid columns="1"
                                            columnClasses="ui-grid-col-12"
                                            layout="grid" styleClass="ui-panelgrid-blank form-group">
			<p:outputLabel id="lang1Lbl" value="#{cc.attrs.label}"
                           for="lang1Input"/>

		<h:panelGroup styleClass="md-inputfield">
          <p:inputTextarea id="lang1Input" readonly="#{cc.attrs.disabled}" autoResize="false" style="resize: none;"
                           cols="#{cc.attrs.cols}" rows="#{cc.attrs.rows}"/>

			<p:commandButton id="moreBtn" icon="ui-icon-translate" original="true" update="extraLangsDlgPnlGrd"
                             process="@this"
                             onclick="PF('extraLangsDlg#{cc.clientId}Var').show();" style="position: absolute;"/>

			</h:panelGroup>

			<p:outputLabel id="lang2Lbl" value="#{cc.attrs.label}" for="lang2Input"/>
			<p:inputTextarea id="lang2Input" readonly="#{cc.attrs.disabled}" autoResize="false" style="resize: none;"
                             cols="#{cc.attrs.cols}" rows="#{cc.attrs.rows}"/>

	</p:panelGrid>

	<p:dialog id="extraLangsDlg" header="#{msg['common.otherLanguages']}" widgetVar="extraLangsDlg#{cc.clientId}Var"
              modal="true"
              closeOnEscape="true">
		<p:defaultCommand target="okBtn" scope="extraLangsDlg" rendered="#{!cc.attrs.disabled}"/>

		<p:panelGrid id="extraLangsDlgPnlGrd" columns="2">
			<f:facet name="footer">
				<p:commandButton id="okBtn" value="#{msg['common.done']}" process="extraLangsDlgPnlGrd"
                                 rendered="#{!cc.attrs.disabled}"
                                 onclick="PF('extraLangsDlg#{cc.clientId}Var').hide();"/>
			</f:facet>
		</p:panelGrid>
	</p:dialog>

	</span>


    <script type="application/javascript">
        $($(PrimeFaces.escapeClientId("#{cc.clientId}:lang1Input"))).keydown(function (e) {
            if ('#{cc.attrs.nextTabindex1}') {
                if (e.keyCode == 9) {
                    $("textarea[id*='#{cc.attrs.nextTabindex1}']").focus();
                    return false;
                }
            }
        });
        $($(PrimeFaces.escapeClientId("#{cc.clientId}:lang2Input"))).keydown(function (e) {
            if ('#{cc.attrs.nextTabindex2}') {
                if (e.keyCode == 9) {
                    $("textarea[id*='#{cc.attrs.nextTabindex2}']").focus();
                    return false;
                }
            }
        });

    </script>
</cc:implementation>

</html>